### ISSUE TITLE
Summary class used in grouping specification overrides `presentation.summary` and provides malformed output

### ISSUE THREAD

**Issue by pratheekrebala** [vespa-engine/vespa#31384] opened 2024-05-31 21:27 UTC
**Describe the bug**

I am unable to set a summary class using `presentation.summary` in queries where a different summary class is used to generate a hitlist inside a `group()` clause. When multiple summary classes are used in this way, the output for fields with highlighting enabled (either through `bold: on` or `dynamic` enabled) is also mangled.

**To Reproduce**
1. Reproduction Code [here](https://github.com/pratheekrebala/vespa-summary-class-repro).
2. I am running the attached query along with `presentation.summary=sample` (N.B. the query has a different summary class `basic` in the `group()` clause.

**Expected behavior**

The responses use the `basic` summary class in the group level hit-list. However, the actual hits (outside the group) also use the `basic` summary class. I was expecting that the actual response would use the `sample` summary class.

**Environment (please complete the following information):**
 - OS: Linux
 - Infrastructure: Self-hosted
 - Versions 22.04
 - Container based on `vespa:8.348.21` with `cuda` and `vespa-onxxruntime` packages installed

**Vespa version**
- 8.348.21

**Comment by pratheekrebala** [comment] 2024-05-31 22:33
Updated with end-end reproduction code here: https://github.com/pratheekrebala/vespa-summary-class-repro

**Comment by pratheekrebala** [comment] 2024-05-31 22:38
I also noticed this weird issue where when I hit the above bug, there's unexpected uni-code separator characters in my response.

**Actual Behavior**:
<img src="https://github.com/vespa-engine/vespa/assets/1174162/14e7217d-999f-4a6d-b73f-ec4a8e96784d" width="300">

**Expected Behavior**:
<img src="https://github.com/vespa-engine/vespa/assets/1174162/a477ce2d-e204-48df-aaae-14ec7acd984e" width="300">

**Comment by baldersheim** [comment] 2024-06-14 16:19
Thanks for reporting. I have made a system test reproducing the error, without requiring docker or pyvespa.
It is indeed a bug. Will figure out root cause over after the weekend.

**Comment by baldersheim** [comment] 2024-06-17 22:01
The override of the summary class was fixed in 8.359.13 with #31592.
What seemed like a well defined and easily reproducible bug turned out to be a clever one. It depended on iteration order. So first take at reproducing by extending existing tests failed. Once fixed we found that 1 of your system tests had a workaround for this issue, so it has been present for a very long time.
Expecting fix to available tomorrow, or the day after, if the build pipeline is in a good mood.

I have not yet verified the bolding/highlighting yet. Keeping it open until until then.

**Comment by baldersheim** [comment] 2024-06-19 14:31
It was indeed 2 separate issues. The garbled output, skipped decoding of backend annotations, is fixed in #31630.
Testcase added in https://github.com/vespa-engine/system-test/pull/4076.
Build pipeline is currently not flowing smoothly. Will update once a release is ready.

**Comment by baldersheim** [comment] 2024-06-19 21:08
Fixes has been merged and verified and will be part of 8.360.23 and on

**Closed by baldersheim** 2024-06-19 21:08 UTC
