### ISSUE TITLE
Seeing an error msg related to config servers after deploying the application zip

### ISSUE THREAD

**Issue by shubh9194** [vespa-engine/vespa#23700] opened 2022-08-17 14:13 UTC
**Describe the bug**
we have single node config server cluster with multiple container and content nodes.
I deployed the application zip with the configs but seeing the following message at the end.
Session 2 for tenant 'default' prepared.
Activating session 2 using http://vespa-1016-pvc-new-0.vespa-1016-pvc-new-internal.d19029.svc.cluster.local:19071/application/v2/tenant/default/session/2/active
Request failed. HTTP status code: 500
Timed out waiting for peer config servers to complete operation (waited for barrier /conig/v2/tenants/default/sessions/2/activeBarrier).Got response from [], but need response rom at least 1 server(s). Timeout passed as argument was 119989 ms
command terminated with exit code 1

**To Reproduce**
We upgraded from older version to 7.589.25 and started seeing this msg

**Expected behavior**
should be getting msg like this
Session 2 for tenant 'default' activated.
Checksum: 369d99258fcf841ce869b982f165af1b
Timestamp: 1657622226930
Generation: 2
**Screenshots**

**Environment (please complete the following information):**
 - Infrastructure: Kubernetes
 - Versions [e.g. 22]

**Vespa version**
7.589.25

**Additional context**

**Comment by jobergum** [comment] 2022-08-18 10:55
See [Configuration server documentation](https://docs.vespa.ai/en/operations/configuration-server.html) and the operations guide. This is usually caused by slow disks (e.g remote network attached storage) and larger applications. 

> ZooKeeper barrier timeout
If the config servers are heavily loaded, or the applications being deployed are big, the internals of the server may time out when synchronizing with the other servers during deploy. To work around, increase the timeout by setting: [VESPA_CONFIGSERVER_ZOOKEEPER_BARRIER_TIMEOUT](https://docs.vespa.ai/en/reference/files-processes-and-ports.html#environment-variables) to 600 (seconds) or higher, and restart the config servers.

**Comment by shubh9194** [comment] 2022-08-22 08:10
I have tried increasing the barrier timeout but still seeing the same error message. Everything works fine in cluster but I this error every time, i deploy the application.zip

**Comment by hmusum** [comment] 2022-08-22 08:42
It would be helpful to see what is in /opt/vespa/logs/vespa/vespa.log and /opt/vespa/logs/vespa/zookeeper.configserver.0.log from start of deployment until it fails.

**Comment by shubh9194** [comment] 2022-08-30 06:48
I have already tried increasing the barrier timeout before but seeing the same error message

**Comment by hmusum** [comment] 2022-08-31 12:05
This is probably a setup/configuration issue, but not enough information to figure out what the issue is. Closing.

**Closed by hmusum** 2022-08-31 12:05 UTC
Labels: question
