### ISSUE TITLE
DELETE request of document API may not be reflected when one of replica nodes is initializing

### ISSUE THREAD

**Issue by riida** [vespa-engine/vespa#13356] opened 2020-05-25 07:04 UTC
Hi.

We have a question about DELETE operation of document API.

## Environment and Setting
- Vespa version is 7.207.47
  - [vespaengine/vespa:7.207.47](https://hub.docker.com/layers/vespaengine/vespa/7.207.47/images/sha256-42cdb695bdc490d3cc2fd4fe216ae09d6b005719cf5184e49d3859f05ecd16b8?context=explore)
- content redundancy is 2
- we check that `.idealstate.merge_bucket.pending` is 0 before stop content node(container)
- we set `Maximum storage transition time` is 20 minutes to avoid pending bucket in release
- document prune age was 2 weeks (default) in our setting

## Problem
We found DELETE operation of document API would not be reflected.
This seems to be happened only when one of replica nodes is initializing (vespa process is running but storage state is not up).
Applying partial update (UPDATE document API and `create: false`) to the document that DELETE operation would be not be reflected, the update was reflected.
This partial update was for the field `indexing: attribute` and `attribute: fast-search`.
The time series was as follows.

```
Container up (Storage Node State is Maintenance) -> DELETE Request -> Storage Node State is Up -> UPDATE Request

* these were in about 30 minutes
```

Document timestamp is the same as UPDATE Request time.
We checked access log and found that both DELETE and UPDATE request returned 200 (StatusOK).

## Question

We expect that the document will not be revival when partial update was applyed after DELETE request returns 200.
Is there any solution for this problem ?

Thanks.

**Comment by jobergum** [comment] 2020-05-25 08:10
>Applying partial update (UPDATE document API and create: false) to the document that DELETE >operation would be not be reflected, the update was reflected.

Could you please try to clarify this sentence, preferably with the sequence of operations, e.g time a send delete for doc x, time b, send update for doc x with create:false. Etc.

**Comment by riida** [comment] 2020-05-25 09:37
Thank you for your quick reply.

Our sequence of operations was as follows.

- [05/08/2020 20:27:06.326] [DELETE](https://docs.vespa.ai/documentation/reference/document-v1-api-reference.html#delete) request for `/document/v1/namespace/doctype/docid/1.hoge`
- [05/08/2020 20:46:19.723] [UPDATE](https://docs.vespa.ai/documentation/reference/document-v1-api-reference.html#update) request for `/document/v1/namespace/doctype/docid/1.hoge`
  - http method is PUT
  - send data-binary is like a below, create field is not specify actually (we expect default is false)
  ```
  {"fields": {"field1": {"assign": {"a": 1} } } }
  ```

DELETE and UPDATE operation were executed by feed client implemented by Golang.

**Comment by jobergum** [comment] 2020-05-25 09:52
So unless create:true was specified with the update the expected behaviour is a NOOP (but with 200 OK as updates against non-existing document will always succeed) and after those two operations a GET request for /document/v1/namespace/doctype/docid/1.hoge should return 404 (Not Found). What is the observed end state?

**Comment by vekterli** [comment] 2020-05-25 10:12
Thank you for the detailed report! I have a suspicion this is an edge case bug with how tombstones interact with updates when replicas are not in sync.

Updates to documents that have out-of-sync replicas shall normally be handled in such a way that they are only applied to the newest document version. This is done by requesting the document from all divergent replica sets and comparing the returned timestamps. However, if the newest version of a document is a _tombstone_ it looks like we today do not propagate sufficient meta-information about this back from the replicas. This means that the update will be erroneously applied against the newest _non-tombstoned_ version and written back to the replicas with a higher timestamp. This effectively resurrects the document, violating operation ordering and consistency.

Here's what I believe has happened in your case:

1. Document is replicated on nodes A and B with timestamp X
1. Node A is set into maintenance mode and taken down. Replica B remains
1. A Delete is written to replica B with timestamp Y > X
1. Node A is taken back up, replicas have not yet been synced
1. An update is received. Replicas are detected as inconsistent and write-repair logic is triggered.
1. Document is requested from nodes A and B. A returns document at X, B returns nil since document is logically deleted. Tombstone presence not properly propagated.
1. Update is performed against document that existed at timestamp X since tombstone at timestamp Y is not accounted for
1. New document version written with timestamp Z > Y to both replicas A and B, effectively hiding the timestamp at Y.

This will only happen when replicas are inconsistent, as Vespa will propagate tombstones to all replicas as quickly as possible, removing older document versions.

I'll create a system test for this edge case to verify this hypothesis. Assuming it holds, I'll start working on a fix ASAP.

**Comment by riida** [comment] 2020-05-25 11:25
Thank you for your detail description.

> after those two operations a GET request for /document/v1/namespace/doctype/docid/1.hoge should return 404 (Not Found). What is the observed end state?

We found that operation GET request for /document/v1/namespace/doctype/docid/1.hoge return 200 (OK) after those two operations.
And we inserted GET operation to check whether document is exists or not before UPDATE request but it did not work well.


We could understand our situation more by your description.

> I'll create a system test for this edge case to verify this hypothesis. Assuming it holds, I'll start working on a fix ASAP.

We expect that your working resolves our problem.

**Comment by vekterli** [comment] 2020-05-27 15:34
A fix has been committed in #13379 and will be part of a Vespa RPM release in the near future. Any version >= 7.228.8 should contain the fix, assuming no regressions. It will pass through our internal testing and deployment pipelines and needs to reach high confidence for some time before it can be made public. This normally only takes a couple of days.

I'll keep this issue open until a version containing the fix is publicly available.

**Comment by vekterli** [comment] 2020-05-29 14:47
@riida Vespa 7.228.15 has just been released. Could confirm if it resolves the problems you have observed?

**Comment by riida** [comment] 2020-06-01 00:27
@vekterli 
Thank you for your working to fix quickly.

We confirm whether new Vespa 7.228.15 resolves our observation.
We will inform you the result after we finish confirmation.

**Comment by riida** [comment] 2020-06-02 07:58
@vekterli 
We have done verification with vespa-7.228.15 but the same problem has happened.

Our system executed rolling update (updating node sequentialy), and we confirmed that the following event series has happened.

1. Document is replicated on nodes A and B with timestamp X
1. [14:14:13.836] Node A is set into maintenance mode and taken down. Replica B remains
1. [14:16:31:923] DELETE operation against document M
1. [14:18:15.833] Node A is taken up (maintenance -> up)
1. Waiting until pending bucket was zero
1. [14:18:32.788] Node B is set into maintenance and taken down. Replica A remains
1. [14:18:47.533] PUT operation (partial update) against document M
1. [14:22:45.085] Node B is taken up (maintenance -> up)
1. Document M is not deleted

We have two question related with above event series.

1. Does pending bucket treat with DELETE operation(tombstone)? 
1. If the node with newer version is maintenance(down), does the update is considered with newer version?

**Comment by vekterli** [comment] 2020-06-02 08:54
@riida thank you for another detailed report!

> Does pending bucket treat with DELETE operation(tombstone)?

Yes, tombstones are explicitly exchanged between nodes as part of replica reconciliation (merge operations). When the "merges pending" metric is zero, tombstones shall be present on all replicas.

> If the node with newer version is maintenance(down), does the update is considered with newer version?

In your case; yes. Since you waited for merges to complete, the newer (tombstone) version on node B should have been copied to node A. When executing the update operation, this is the version the update should have been applied against.

What you're observing is certainly not the intended behavior. We have system tests for explicitly testing the behavior of [Put](https://github.com/vespa-engine/system-test/blob/master/tests/vds/merging.rb), [Update](https://github.com/vespa-engine/system-test/blob/master/tests/search/inconsistent_replicas/updates_to_inconsistent_buckets.rb) and [Remove](https://github.com/vespa-engine/system-test/blob/master/tests/vds/removewhilenodedown/visitremoveddocs.rb) operations in the presence of node failures. I'm not sure if we have tests for the exact case you mentioned. If not, I will add it and see if I can reproduce your results locally.

**Comment by riida** [comment] 2020-06-02 11:33
@vekterli 
Thank you for your answer to my questions.

We understand that our case is not intended behavior. 

We will try to review whether the program waiting for pending bucket is zero works well.

Currently, we check the `vds.idealstate.merge_bucket.pending` (`.values.last`) metric of all distributor status page (`/state/v1/metrics`).
Is this procedure is no problem?

**Comment by vekterli** [comment] 2020-06-02 12:10
>Currently, we check the `vds.idealstate.merge_bucket.pending` (`.values.last`) metric of all >distributor status page (`/state/v1/metrics`).
>Is this procedure is no problem?

Yes that should work fine.

An alternative approach is to modify node states using what we refer to as "safe mode", which delegates all this work to the cluster controller component. The cluster controller already receives and aggregates metrics from all nodes. Setting a node into maintenance with safe mode enabled _only_ allows the transition to happen if the system is considered in sync.

If you're using `vespa-set-node-state`, using safe mode is as easy as adding `--safe` as a command line parameter:
```
$ vespa-set-node-state --help
(...)
 -a --safe                : Only carries out state changes if deemed safe by the
                            cluster controller. For maintenance mode, will also
                            set the distributor with the same distribution key
                            to down atomically as part of the same state change.
                            For up mode, transition is only allowed if the
                            content node reports itself as up. Only supported
                            for type storage.
(...)
```

If you're using the [cluster controller state management REST API](https://docs.vespa.ai/documentation/content/api-state-rest-api.html) directly, you can add
```json
"condition": "safe"
```
to the top-level request JSON object. This is not currently publicly documented, but it's what we use internally for our orchestrated upgrades/restarts.

**Comment by vekterli** [comment] 2020-06-02 13:57
I am currently not able to reproduce this locally using the test added in https://github.com/vespa-engine/system-test/pull/765

Here's a summary of the events and results from the test. Note that I've added dumping of replica state using `vespa-stat --document <doc id> --dump` for debugging purposes.

Initial state: nodes 0 and 1 are in state Up, redundancy is 2.

Note: I'm intermixing parts of Ruby test code and console output here. Sorry for the mess.
### 1. Feed initial document
```ruby
http_post('/document/v1/storage_test/music/number/1/foo', '{"fields":{"title":"first title","artist":"cool dude"}}'
```
```
$ vespa-stat --document id:storage_test:music:n=1:foo --dump
Bucket maps to the following actual files:
	BucketInfo(BucketId(0x2000000000000001): [distributor:0] [node(idx=0,crc=0xa1d71e26,docs=1/1,bytes=185/185,trusted=true,active=true,ready=true), node(idx=1,crc=0xa1d71e26,docs=1/1,bytes=185/185,trusted=true,active=false,ready=true)])

Details for BucketId(0x2000000000000001):
	Bucket information from node 0:
Persistence bucket BucketId(0x2000000000000001), partition 0
  Timestamp: 1591097190000000, Doc(id:storage_test:music:n=1:foo), gid(0x01000000b575b0d0d8db50a2), size: 185


	Bucket information from node 1:
Persistence bucket BucketId(0x2000000000000001), partition 0
  Timestamp: 1591097190000000, Doc(id:storage_test:music:n=1:foo), gid(0x01000000b575b0d0d8db50a2), size: 185
```
Document is persisted to both nodes as expected with timestamp 1591097190000000.

### 2. Take down node 1 and remove document with single replica present
(state REST API invoked to take node 1 down)
```ruby
http_delete('/document/v1/storage_test/music/number/1/foo')
```
```
$ vespa-stat --document id:storage_test:music:n=1:foo --dump
Bucket maps to the following actual files:
	BucketInfo(BucketId(0x2000000000000001): [distributor:0] [node(idx=0,crc=0x0,docs=0/1,bytes=0/30,trusted=true,active=true,ready=true)])

Details for BucketId(0x2000000000000001):
	Bucket information from node 0:
Persistence bucket BucketId(0x2000000000000001), partition 0
  Timestamp: 1591097196000001, id:storage_test:music:n=1:foo, gid(0x01000000b575b0d0d8db50a2) (remove)
```
Here we see a single replica active on node 0, containing a remove entry (tombstone) for the document. This tombstone has timestamp 1591097196000001, which is greater than 1591097190000000.

### 3. Take node 1 back up and allow merges to complete
(state REST API invoked to take node 1 up)
(wait for merge completion)
```
$ vespa-stat --document id:storage_test:music:n=1:foo --dump
Bucket maps to the following actual files:
	BucketInfo(BucketId(0x2000000000000001): [distributor:0] [node(idx=0,crc=0x0,docs=0/1,bytes=0/30,trusted=true,active=true,ready=true), node(idx=1,crc=0x0,docs=0/1,bytes=0/30,trusted=true,active=false,ready=true)])

Details for BucketId(0x2000000000000001):
	Bucket information from node 0:
Persistence bucket BucketId(0x2000000000000001), partition 0
  Timestamp: 1591097196000001, id:storage_test:music:n=1:foo, gid(0x01000000b575b0d0d8db50a2) (remove)


	Bucket information from node 1:
Persistence bucket BucketId(0x2000000000000001), partition 0
  Timestamp: 1591097196000001, id:storage_test:music:n=1:foo, gid(0x01000000b575b0d0d8db50a2) (remove)
```
Tombstone at timestamp 1591097196000001 has now been propagated to node 1, overwriting the old document version.

### 4. Take node 0 down and ensure update is a no-op
(state REST API invoked to take node 0 down)
```ruby
http_put('/document/v1/storage_test/music/number/1/foo?create=false', '{"fields":{"title":{"assign":"uh oh"}}}'
```
```
$ vespa-stat --document id:storage_test:music:n=1:foo --dump
Bucket maps to the following actual files:
	BucketInfo(BucketId(0x2000000000000001): [distributor:0] [node(idx=1,crc=0x0,docs=0/1,bytes=0/30,trusted=true,active=true,ready=true)])

Details for BucketId(0x2000000000000001):
	Bucket information from node 1:
Persistence bucket BucketId(0x2000000000000001), partition 0
  Timestamp: 1591097196000001, id:storage_test:music:n=1:foo, gid(0x01000000b575b0d0d8db50a2) (remove)
```
The update operation has _not_ been applied to the replica. This is the expected behavior.

@riida would it be possible for you to try running the `vespa-stat` command to observe the state of the document replicas in a similar fashion? I'd be very interested to know what I'm missing. Also please let me know if this test does not sufficiently model your observations.

**Comment by riida** [comment] 2020-06-02 14:27
@vekterli 
Thank you for proposing another approach.

We didn't set a node into maintenance mode explicitly because we extend `Maximum storage transition time` to 20 minutes.
And we didn't know "safe mode". 
We will try to set a node state maintenance mode before node down by `vespa-set-node-statel` with `--safe` option.

> would it be possible for you to try running the vespa-stat command to observe the state of the document replicas in a similar fashion?
> I'd be very interested to know what I'm missing. Also please let me know if this test does not sufficiently model your observations.

I think that your local test result suffciently reproduce our observation.
So our observation was certainly not the intended behavior according to your local test result.

Our observation occured in high traffic production environment.
(Somtimes, deleted document is recreated by POST request which is truely creating request.)
So we don't know that we can definitely share the result you want, but we try to capture the state of the document replicas!

**Comment by riida** [comment] 2020-06-05 10:49
@vekterli 
We checked the same procedure you showed in our test environment.
As a result, the last partial update (step 4 in your test) has not been applied to the replica.

So we suspect that our pending bucket waiting logic does not work well.

We are testing `vespa-set-node-state --safe`, and we have one question about node state transition.  
It seems that cluster controller marked node down before maximum storage transition time exceeded when node state was changed into UP (User state).
We set Maximum storage transition time to 20 minutes.
Is this expected behavior?

Cluster controller event logs is below.

Date (UTC) | Type | Node | Bucket space | Event
-- | -- | -- | -- | --
2020-06-05 10:21:37.361 | CURRENT | storage.0 | - | Altered node state in cluster state from 'U, t 1591352435, b 10' to 'U, b 10'
2020-06-05 10:21:37.348 | CURRENT | storage.0 | - | Altered node state in cluster state from 'D, b 10: controlled shutdown' to 'U, t 1591352435, b 10'
2020-06-05 10:21:37.347 | REPORTED | storage.0 | - | Now reporting state U, t 1591352435, b 10
2020-06-05 10:21:36.043 | REPORTED | storage.0 | - | Node got back into slobrok with same address as before: tcp/dev-vespa-content00.test:19103
2020-06-05 10:20:25.945 | CURRENT | storage.0 | - | Altered node state in cluster state from 'M, b 10' to 'D, b 10: controlled shutdown'
2020-06-05 10:20:25.945 | CURRENT | storage.0 | - | Exceeded implicit maintenance mode grace period of 1200000 milliseconds. Marking node down.
2020-06-05 10:20:25.943 | REPORTED | storage.0 | - | Wanted state Up, but we cannot force node into that state yet as it is currently in Down, start timestamp 1591282606, minimum used bits 10, disk states: disk 0: DiskState(u): controlled shutdown
2020-06-05 10:19:51.912 | REPORTED | storage.0 | - | Failed to get node state: D, t 1591282606, b 10: controlled shutdown
2020-06-05 10:19:51.912 | REPORTED | storage.0 | - | Failed to get node state: D, t 1591282606, b 10: controlled shutdown
2020-06-05 10:19:51.912 | REPORTED | storage.0 | - | Node is no longer in slobrok. No pending state request to node.
2020-06-05 10:19:51.811 | REPORTED | storage.0 | - | Now reporting state S, t 1591282606, b 10: controlled shutdown
2020-06-05 10:19:42.206 | CURRENT | storage.0 | - | Altered node state in cluster state from 'U, b 10' to 'M, b 10'
2020-06-05 10:19:42.203 | WANTED | storage.0 | - | Node state set to Maintenance.

**Comment by riida** [comment] 2020-06-09 10:08
@vekterli 
> From the timeline you've presented it looks like there might be an edge case where the configured limit is not respected when a node is marked as Up. I'll take a look.

We'd be glad to know the cause if possible.

> Note that using safe mode is recommended rather than relying on maximum storage transition time.
...

Thank you for your detailed description.

It was very helpful, and we've learned the logic of node state transition more.

We used safe mode when changing node state against both Maintenance and Up from your advise,
and we have not found the problem including the deleted document revival.

We will operate our system which uses safe mode state transition,
and we will continue to observe that any problem does not occur.

**Comment by vekterli** [comment] 2020-07-06 15:11
I'm closing this issue since the root underlying problem related to gets/updates with tombstones shall have been fixed.

@riida thank you for your detailed reports and follow-ups! Please create an issue if you observe any other problems or strange system behaviors.

**Closed by vekterli** 2020-07-06 15:11 UTC
Labels: bug
