### ISSUE TITLE
Low recall on bfloat16 exact vector search with more than one thread per search 

### ISSUE THREAD

**Issue by crstp** [vespa-engine/vespa#28036] opened 2023-08-14 09:05 UTC
**Describe the bug**
When embeddings are indexed with bfloat16, the ANN search works fine but the exact search has a low recall.

**To Reproduce**
1. Start Vespa.
```
docker run --detach --name vespa --hostname vespa-container \
  --publish 8080:8080 --publish 19071:19071 \
  vespaengine/vespa
```
2. Deploy the following schema
```
schema dictionary_doc {
    document dictionary_doc {
        field doc_embedding type tensor<float>(d0[768]) {
            indexing: index | attribute
            attribute {
                distance-metric: prenormalized-angular
            }
            index {
                hnsw {
                    max-links-per-node: 16
                    neighbors-to-explore-at-insert: 100
                }
            }
        }
        field doc_embeddingb16 type tensor<bfloat16>(d0[768]) {
            indexing: index | attribute
            attribute {
                distance-metric: prenormalized-angular
            }
            index {
                hnsw {
                    max-links-per-node: 16
                    neighbors-to-explore-at-insert: 100
                }
            }
        }
        field filter_range type int {
            indexing: summary | attribute
            attribute: fast-search
        }
    }

    rank-profile embedding_ranking {
        inputs {
            query(query_embedding) tensor<float>(d0[768])
        }
    }

    rank-profile doc_embedding_ranking inherits embedding_ranking {
        first-phase {
            expression: 1 - distance(field, doc_embedding) / 2
        }
    }

    rank-profile doc_embeddingb16_ranking inherits embedding_ranking {
        first-phase {
            expression: 1 - distance(field, doc_embeddingb16) / 2
        }
    }
}
```

3. Index 10k words with the following code. 
```
pip3 install sentence_transformers pyvespa
wget https://raw.githubusercontent.com/dwyl/english-words/master/words_dictionary.json
```

https://github.com/crstp/vespa-bfloat16-exact-search-reproduce-issue/blob/main/vespa_bfloat16_exact_index.py

4. Query embeddings with the following code

https://github.com/crstp/vespa-bfloat16-exact-search-reproduce-issue/blob/main/vespa_bfloat16_exact_query.py

**Expected behavior**
Recall of bfloat16 exact search should be nearly 1

**Actual behavior**
Got low recall only on the exact search.
```
Normal recall: 1.0, Float16 ANN recall: 1.0, Float16 exact recall: 0.12
Normal recall: 0.85, Float16 ANN recall: 0.84, Float16 exact recall: 0.1
Normal recall: 0.92, Float16 ANN recall: 0.91, Float16 exact recall: 0.08
Normal recall: 0.92, Float16 ANN recall: 0.96, Float16 exact recall: 0.11
Normal recall: 0.92, Float16 ANN recall: 0.92, Float16 exact recall: 0.06
...
```

**Environment (please complete the following information):**
 - OS: Ubuntu
 - Infrastructure: Local docker container
 - Versions: 22.04

**Vespa version**
8.209.11

**Comment by jobergum** [comment] 2023-08-14 11:22
Thank you for the detailed description and reproducing steps - it worked without a hiccup. 


Since I have used `bfloat16` a lot, this was a surprising read, so I jumped to try to reproduce it, but in my env the output is as expected (without looking in detail at the query script). 

```
Normal recall: 0.95, Float16 ANN recall: 0.96, Float16 exact recall: 1.0
Normal recall: 0.9, Float16 ANN recall: 0.91, Float16 exact recall: 1.0
Normal recall: 0.88, Float16 ANN recall: 0.87, Float16 exact recall: 1.0
Normal recall: 0.94, Float16 ANN recall: 0.93, Float16 exact recall: 1.0
Normal recall: 0.81, Float16 ANN recall: 0.82, Float16 exact recall: 1.0
Normal recall: 0.95, Float16 ANN recall: 0.94, Float16 exact recall: 0.99
Normal recall: 0.73, Float16 ANN recall: 0.73, Float16 exact recall: 0.99
Normal recall: 0.93, Float16 ANN recall: 0.93, Float16 exact recall: 1.0
Normal recall: 0.87, Float16 ANN recall: 0.87, Float16 exact recall: 1.0
Normal recall: 0.96, Float16 ANN recall: 0.96, Float16 exact recall: 1.0
Normal recall: 0.91, Float16 ANN recall: 0.91, Float16 exact recall: 1.0
Normal recall: 0.88, Float16 ANN recall: 0.87, Float16 exact recall: 1.0
Normal recall: 0.87, Float16 ANN recall: 0.85, Float16 exact recall: 1.0
Normal recall: 0.92, Float16 ANN recall: 0.91, Float16 exact recall: 1.0
Normal recall: 0.86, Float16 ANN recall: 0.86, Float16 exact recall: 1.0
Normal recall: 0.89, Float16 ANN recall: 0.89, Float16 exact recall: 1.0
Normal recall: 0.92, Float16 ANN recall: 0.92, Float16 exact recall: 1.0
Normal recall: 0.93, Float16 ANN recall: 0.93, Float16 exact recall: 1.0
Normal recall: 0.97, Float16 ANN recall: 0.97, Float16 exact recall: 1.0
Normal recall: 0.91, Float16 ANN recall: 0.91, Float16 exact recall: 1.0
Normal recall: 0.9, Float16 ANN recall: 0.9, Float16 exact recall: 1.0
```

**Comment by crstp** [comment] 2023-08-14 12:02
Thanks for quickly checking it!

I've looked at the setup again and realized I have a custom `searchnode.requestthreads.persearch`.

So I've tried setting `ranking.matching.numThreadsPerSearch` to 1 in the query script and the exact search worked just fine - but when it's bigger than 1, the recall dropped significantly.

`ranking.matching.numThreadsPerSearch=1`
```
Normal recall: 0.99, Float16 ANN recall: 0.99, Float16 exact recall: 1.0
Normal recall: 0.82, Float16 ANN recall: 0.83, Float16 exact recall: 1.0
Normal recall: 0.9, Float16 ANN recall: 0.9, Float16 exact recall: 1.0
Normal recall: 0.95, Float16 ANN recall: 0.95, Float16 exact recall: 1.0
```

`ranking.matching.numThreadsPerSearch=2`

```
Normal recall: 0.99, Float16 ANN recall: 0.99, Float16 exact recall: 0.39
Normal recall: 0.82, Float16 ANN recall: 0.83, Float16 exact recall: 0.53
Normal recall: 0.9, Float16 ANN recall: 0.9, Float16 exact recall: 0.52
Normal recall: 0.95, Float16 ANN recall: 0.95, Float16 exact recall: 0.48
```


services.xml:

```
<?xml version='1.0' encoding='UTF-8'?>
<!-- Copyright Yahoo. Licensed under the terms of the Apache 2.0 license. See LICENSE in the project root. -->
<services version="1.0" xmlns:deploy="vespa" xmlns:preprocess="properties">

    <container id='default' version='1.0'>
        <search></search>
        <document-api></document-api>
        <nodes>
            <node hostalias='node1'></node>
            <jvm options="-Xms8g -Xmx8g -XX:+PrintCommandLineFlags -XX:+PrintGC"
                 gc-options="-XX:+UseG1GC -XX:MaxTenuringThreshold=15"/>
        </nodes>
    </container>

    <content id='mind' version='1.0'>
        <engine>
            <proton>
                <tuning>
                    <searchnode>
                        <requestthreads>
                            <persearch>8</persearch>
                        </requestthreads>
                    </searchnode>
                </tuning>
            </proton>
        </engine>
        <redundancy>1</redundancy>
        <documents>
            <document type='dictionary_doc' mode="index"/>
        </documents>
        <nodes>
            <node hostalias="node1" distribution-key="0"/>
        </nodes>
    </content>

</services>
```

query-profiles (probably unrelated)
```
<query-profile id="default" type="root">
    <field name="maxHits">50000</field>
    <field name="timeout">10</field>
</query-profile>
```

**Comment by jobergum** [comment] 2023-08-14 12:18
Thank you for adding that detail. I can reproduce the behavior when using more than one thread per search.

 Any thoughts on this @havardpe or  @arnej27959 ?

**Comment by havardpe** [comment] 2023-08-14 14:01
There is a bug;
The distance function is shared between all search threads in the brute force case (ANN is always single threaded). A scratch area is used to convert cell types when needed (which is triggered by the bfloat16 case). All search threads will write to the same scratch area, trashing each others results. This effect can be seen by the recall going down when the number of threads go up.

**Comment by geirst** [comment] 2023-08-16 11:06
This is fixed in Vespa 8.212.18 (https://github.com/vespa-engine/vespa/pull/28046).

**Closed by geirst** 2023-08-16 11:06 UTC

**Comment by jobergum** [comment] 2023-08-17 09:14
Hey @crstp, 8.212.18 which has a fix for this issue is now [released](https://hub.docker.com/layers/vespaengine/vespa/8.212.18/images/sha256-176c717b947aa70dae74f045fbb253e393bd3785bfaf2d138f4c50633f286a85?context=explore). Again, thank you very much for this detailed bug report!

**Comment by crstp** [comment] 2023-08-17 09:44
Thank you so much @jobergum and @geirst for fixing it quickly! Will try the new version
