### ISSUE TITLE
Query optimizer removes query terms when using &recall parameter and sddocname

### ISSUE THREAD

**Issue by jobergum** [vespa-engine/vespa#11975] opened 2020-01-28 08:59 UTC
When using the &recall parameter which is mainly used for scraping rank features we observe an incorrect query rewrite when using sddocname as match all documents filter. 

```
select * from sources * where ((default contains "cars" OR default contains "b" OR default contains "c" OR sddocname contains "product") AND id = ([{"filter": true, "ranked": false}]100012));]
```

Is re-written to 

```
select * from sources * where id = ([{"id": 5, "filter": true, "ranked": false}]100012);
```

**Comment by bratseth** [comment] 2020-01-31 15:43
I cannot reproduce this behavior, let me know if you have it running.

**Comment by jobergum** [comment] 2020-02-03 08:56
Yes. 
```
http://localhost:8080/search/?query=(cars%20b%20c%20%20sddocname:product)&ranking=dump&tracelevel=3&recall=%2Bid:100012

``` 

Outputs https://gist.githubusercontent.com/jobergum/39ecfd686efe9c44972346385ccee9d3/raw/60f74b9d60a23aa2a5d72ea2b09bb217f2da8d1b/trace.json

**Comment by bratseth** [comment] 2020-02-03 12:25
Helpful, thanks. Fixed in https://github.com/vespa-engine/vespa/pull/12045

**Closed** 2020-02-03 12:25 UTC
