### ISSUE TITLE
Unable to set top-k-probability as 1.0

### ISSUE THREAD

**Issue by adityaverma21** [vespa-engine/vespa#31715] opened 2024-06-25 10:58 UTC
**Describe the bug**
Unable to set top-k-probability as 1.0

https://github.com/vespa-engine/vespa/issues/31638 

Still running into the same issue

My services.xml content

```
<content id="mydoc" version="1.0">
<redundancy>1</redundancy>
<engine>
<proton>
<resource-limits> </resource-limits>
<searchable-copies>1</searchable-copies>
<tuning>
<searchnode>
<feeding>
<concurrency>1.0</concurrency>
</feeding>
<requestthreads>
<search>8</search>
<persearch>4</persearch>
<summary>4</summary>
</requestthreads>
<flushstrategy>
<native>
<component>
<maxage>86400</maxage>
</component>
</native>
</flushstrategy>
</searchnode>
</tuning>
<sync-transactionlog>true</sync-transactionlog>
</proton>
</engine>
<tuning>
<cluster-controller>
<transition-time>3600</transition-time>
</cluster-controller>
<min-node-ratio-per-group>1</min-node-ratio-per-group>
<dispatch>
<top-k-probability>1.0</top-k-probability>
</dispatch>
</tuning>
<documents>
...
</documents>
</content>
```

**Comment by geirst** [comment] 2024-06-26 11:03
Closing as a duplicate of https://github.com/vespa-engine/vespa/issues/31638.

**Closed by geirst** 2024-06-26 11:03 UTC
