### ISSUE TITLE
Registering a concrete type class breaks indexing of array<string>

### ISSUE THREAD

**Issue by angelf** [vespa-engine/vespa#23125] opened 2022-06-16 09:02 UTC
**Describe the bug**
When a concrete type class is created using _vespa-documentgen-plugin_, and then registered in services.xml, `array<string>` fields with `{indexing: index}` stop being indexed.

**To Reproduce**
A full reproduction repo is available at https://github.com/angelf/vespa-bug-report. In summary

1. Add a field of type `array<string>` with `{indexing: index}` to a schema and verify that search by that field works as expected
2. Register a concrete class generated with _vespa-documentgen-plugin_ in services.xml with the `<document>` tag
3. Search by the field of type `array<string>` (YQL or userQuery)
4. The field stops matching
5. Other fields (for example of type `string`) are not affected - search works as expected for those

Note that:
* PUT-ing documents does not show any error,
* there are no messages in vespa.log
* The generated document classes work as expected elsewhere (for example, they can be used fine in docproc: documents will get the correct class and can be manipulated using concrete classes)

**Expected behavior**
Search results should not be affected at all by registering a concrete type class. 

**Environment (please complete the following information):**
I'm using ghcr.io/vespa-engine/vespa-arm64-preview on a Apple Silicon Mac

**Vespa version**
* vespa on docker: [7.594.36](https://github.com/orgs/vespa-engine/packages/container/vespa-arm64-preview/24557344?tag=7.594.36)
* vespa-documentgen-plugin used at generation: 7.594.36

**Comment by jobergum** [comment] 2022-06-23 08:57
Yes, I've reproduced this.  The reason we have probably not spotted this before is that `attribute` has typically been used for array string fields. `attribute` implies `match:word`. Single valued strings (which are more commonly used with `index`) are handled as expected. What happens is that the indexing document processor does not tokenize the field, and instead indexes the entire content 'foo bar' as an entry in the dictionary, this then breaks for searching as the search will tokenize. 

```
[{
    "put": "id:test:news::stack",
    "fields": {
        "title": ["foo bar"],
        "description": "foo bar"
    }
}]

```
Results in 

```
vespa-index-inspect dumpwords --indexdir index.flush.2/ --field title
foo bar	1
vespa-index-inspect dumpwords --indexdir index.flush.2/ --field description
bar	1
foo	1
```

I also notice this from your pom.xml which is another problem we should address

```
 <!-- Turns out that vespa codegen generates code that raises warnings, which in turn make the project fail
            (-wError is implicitly set?). This is solved by injeciting a @SuppressWarnings at the begining of each generated
            class
            -->
            <plugin>
                <groupId>com.google.code.maven-replacer-plugin</groupId>
                <artifactId>maven-replacer-plugin</artifactId>
                <version>1.3.2</version>
                <executions>
                    <execution>
                        <phase>prepare-package</phase>
                        <goals>
                            <goal>replace</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <includes>
                        <include>target/generated-sources/vespa-documentgen-plugin</include>
                    </includes>

                    <regex>true</regex>
                    <regexFlags>
                        <regexFlag>MULTILINE</regexFlag>
                    </regexFlags>

                    <replacements>
                        <replacement>
                            <token>^(@SuppressWarnings\(.*?\)\s+)?public class</token>
                            <value>@SuppressWarnings("all") public class</value>
                        </replacement>
                    </replacements>
                </configuration>
            </plugin>
```

**Comment by angelf** [comment] 2022-06-26 10:51
Lovely, great thanks for investigating this.

**Comment by arnej27959** [comment] 2023-01-05 14:27
This is fixed by
https://github.com/vespa-engine/vespa/pull/25404

You need to switch to using docker.io/vespaengine/vespa (it has arm64 support already) to get a
newer vespa version; the fix should be in the next release (version >= 8.107.8).

Note that the problems where you needed to add `@SuppressWarnings` should be fixed already in Vespa 8.

This bug was caused by interaction between concrete document types and the indexing document processor.
Since concrete documents store `array<string>` straight-forward as a Java `List<String>` it's not possible
to add the tokenization information necessary in order to index individual words in each string.  Converting back
to the canonical format fixes this entire class of problems.

**Comment by arnej27959** [comment] 2023-01-11 14:52
version with fix is now available from docker.

**Closed** 2023-01-11 14:52 UTC
