### ISSUE TITLE
Documentation search doesn't work due to trying to load unsafe scripts

### ISSUE THREAD

**Issue by jazoom** [vespa-engine/vespa#5661] opened 2018-04-22 00:53 UTC
Using Chrome I was able to get search to work in the documentation by explicitly allowing the running of unsafe scripts on the page.

>Mixed Content: The page at 'https://docs.vespa.ai/search.html?q=endpoint' was loaded over HTTPS, but requested an insecure script 'http://doc-search.vespa.ai/vespa_documentation_search_proxy/search/?jsoncallback=jQuery224035767742119236035_1524358332030&query=endpoint&hits=400&ranking=documentation&_=1524358332031'. This content should also be served over HTTPS.

**Comment by frodelu** [comment] 2018-04-25 12:12
This is a duplicate of #5506 - closing.

**Closed by frodelu** 2018-04-25 12:12 UTC
