### ISSUE TITLE
Container server start error with single bundle and vespa version >= 8.86.28

### ISSUE THREAD

**Issue by codycollier** [vespa-engine/vespa#26821] opened 2023-04-21 19:27 UTC
**Describe the bug**

Short version:

With 8.86.28 or higher, a simple app with a single java component/bundle leads
to a container start error `Could not install bundle with reference...`.

**Environment (please complete the following information):**
 - OS: mac os x monterrey 12
 - Infrastructure: docker for mac

**Detailed Description**

I'm running into a problem with an application which includes a single and
fairly simple bundle. In version `8.83.34` and prior, this application works
fine. As soon as the vespa container and the vespa version in pom are updated
to `8.86.28`, problems arise.  Specifically, the following happens:

1. start a fresh, empty vespa instance in 8.86.28 (or higher, like 8.153.19)
2. mvn package
3. vespa deploy (using the vespa cli tool)
4. config server response with success and new generation
5. the container service attempts to start with the new generation
6. the container service stops due to errors, short version:

```
warning Failed to set up first component graph
java.lang.RuntimeException: Could not install bundle with reference 'file '5aaebad1c9543dcc'
...
Caused by: java.util.zip.ZipException: zip END header not found
```

The full trace is down below, along with a snapshot of the file tree inside
of the corresponding filedistribution directory. As best I can tell, something
new was introduced in 8.86.28 and the way I'm building the package with the
bundle is no longer compatible.

Numerous things have already been tested like the versions of maven, openjdk,
and so on. I've even inspected the component jar from inside the running vespa
container and it seems fine (it extracts, can be added to a classpath, etc).

To help with debugging, I made a simplistic application that still expresses
the error.

Attached you'll find that bare bones application with the following characteristics:

* single node, single minimal schema
* minimal pom.xml from the vespa docs
* minor addition to pom to ensure target versions of 17
* no java files, just builds an empty bundle/jar aside from metadata
* no references to the bundle in services.xml

This app expresses the problem in the same way I see with the real application
which has a searcher and docproc inside.

Is there something I'm overlooking, or did something change with the app
bundle loading?

Debugging details:

```
docker releases:
* 8.153.19  - error
* 8.86.28   - error
* 8.83.34   - works fine
```

```
1682102917.903972	564557cb9159	974/1	container	Container.com.yahoo.container.core.config.HandlersConfigurerDi	info	Installing bundles for application generation 2
1682102917.911170	564557cb9159	974/1	container	Container.com.yahoo.container.core.config.ApplicationBundleLoader	info	Installing bundle with reference '5aaebad1c9543dcc'
1682102918.045172	564557cb9159	974/1	container	Container.com.yahoo.container.di.Container	warning	Failed to set up component graph - uninstalling latest bundles. Bootstrap generation: 2
1682102918.051244	564557cb9159	974/1	container	Container.com.yahoo.container.di.Container	warning	Failed to set up first component graph
exception=
java.lang.RuntimeException: Could not install bundle with reference 'file '5aaebad1c9543dcc''
    at com.yahoo.container.core.config.ApplicationBundleLoader.installWithFileDistribution(ApplicationBundleLoader.java:175)
    at com.yahoo.container.core.config.ApplicationBundleLoader.installBundles(ApplicationBundleLoader.java:149)
    at com.yahoo.container.core.config.ApplicationBundleLoader.useBundles(ApplicationBundleLoader.java:62)
    at com.yahoo.container.core.config.HandlersConfigurerDi$ContainerAndDiOsgi.useApplicationBundles(HandlersConfigurerDi.java:103)
    at com.yahoo.container.di.Container.installApplicationBundles(Container.java:205)
    at com.yahoo.container.di.Container.waitForNewConfigGenAndCreateGraph(Container.java:133)
    at com.yahoo.container.di.Container.waitForNextGraphGeneration(Container.java:75)
    at com.yahoo.container.core.config.HandlersConfigurerDi.waitForNextGraphGeneration(HandlersConfigurerDi.java:117)
    at com.yahoo.container.core.config.HandlersConfigurerDi.<init>(HandlersConfigurerDi.java:73)
    at com.yahoo.container.core.config.HandlersConfigurerDi.<init>(HandlersConfigurerDi.java:59)
    at com.yahoo.container.jdisc.ConfiguredApplication.createConfigurer(ConfiguredApplication.java:409)
    at com.yahoo.container.jdisc.ConfiguredApplication.start(ConfiguredApplication.java:168)
    at com.yahoo.jdisc.core.ApplicationLoader.start(ApplicationLoader.java:157)
    at com.yahoo.jdisc.core.StandaloneMain.run(StandaloneMain.java:41)
    at com.yahoo.jdisc.core.StandaloneMain.main(StandaloneMain.java:33)
Caused by: java.lang.RuntimeException: com.yahoo.jdisc.application.BundleInstallationException: Unable to cache bundle: file:/opt/vespa/var/db/vespa/filedistribution/5aaebad1c9543dcc/writing18378621176289283731
    at com.yahoo.osgi.OsgiImpl.install(OsgiImpl.java:156)
    at com.yahoo.container.core.config.FileAcquirerBundleInstaller.installBundles(FileAcquirerBundleInstaller.java:48)
    at com.yahoo.container.core.config.ApplicationBundleLoader.installWithFileDistribution(ApplicationBundleLoader.java:163)
    ... 14 more
Caused by: com.yahoo.jdisc.application.BundleInstallationException: Unable to cache bundle: file:/opt/vespa/var/db/vespa/filedistribution/5aaebad1c9543dcc/writing18378621176289283731
    at com.yahoo.jdisc.core.FelixFramework.installBundle(FelixFramework.java:87)
    at com.yahoo.osgi.OsgiImpl.install(OsgiImpl.java:154)
    ... 16 more
Caused by: org.osgi.framework.BundleException: Unable to cache bundle: file:/opt/vespa/var/db/vespa/filedistribution/5aaebad1c9543dcc/writing18378621176289283731
    at org.apache.felix.framework.Felix.installBundle(Felix.java:3258)
    at org.apache.felix.framework.BundleContextImpl.installBundle(BundleContextImpl.java:147)
    at org.apache.felix.framework.BundleContextImpl.installBundle(BundleContextImpl.java:120)
    at com.yahoo.jdisc.core.FelixFramework.installBundle(FelixFramework.java:183)
    at com.yahoo.jdisc.core.FelixFramework.installBundle(FelixFramework.java:85)
    ... 17 more
Caused by: java.util.zip.ZipException: zip END header not found
    at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1469)
    at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1477)
    at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1315)
    at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1277)
    at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:709)
    at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:243)
    at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:172)
    at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:186)
    at org.apache.felix.framework.util.SecureAction.openZipFile(SecureAction.java:802)
    at org.apache.felix.framework.util.WeakZipFileFactory$WeakZipFile.<init>(WeakZipFileFactory.java:169)
    at org.apache.felix.framework.util.WeakZipFileFactory$WeakZipFile.<init>(WeakZipFileFactory.java:151)
    at org.apache.felix.framework.util.WeakZipFileFactory.create(WeakZipFileFactory.java:78)
    at org.apache.felix.framework.cache.JarRevision.<init>(JarRevision.java:83)
    at org.apache.felix.framework.cache.BundleArchive.createRevisionFromLocation(BundleArchive.java:819)
    at org.apache.felix.framework.cache.BundleArchive.reviseInternal(BundleArchive.java:491)
    at org.apache.felix.framework.cache.BundleArchive.<init>(BundleArchive.java:155)
    at org.apache.felix.framework.cache.BundleCache.create(BundleCache.java:456)
    at org.apache.felix.framework.Felix.installBundle(Felix.java:3254)
    ... 21 more

1682102918.042911	564557cb9159	1005/1	metricsproxy-container	Container.com.yahoo.metrics.simple.MetricManager	config	setting up simple metrics gathering. reportPeriodSeconds=60, pointsToKeepPerMetric=100
1682102918.059365	564557cb9159	974/1	container	Container.com.yahoo.jdisc.core.ApplicationLoader	warning	Exception thrown while activating application.
exception=
java.lang.RuntimeException: Could not install bundle with reference 'file '5aaebad1c9543dcc''
    at com.yahoo.container.core.config.ApplicationBundleLoader.installWithFileDistribution(ApplicationBundleLoader.java:175)
    at com.yahoo.container.core.config.ApplicationBundleLoader.installBundles(ApplicationBundleLoader.java:149)
    at com.yahoo.container.core.config.ApplicationBundleLoader.useBundles(ApplicationBundleLoader.java:62)
    at com.yahoo.container.core.config.HandlersConfigurerDi$ContainerAndDiOsgi.useApplicationBundles(HandlersConfigurerDi.java:103)
    at com.yahoo.container.di.Container.installApplicationBundles(Container.java:205)
    at com.yahoo.container.di.Container.waitForNewConfigGenAndCreateGraph(Container.java:133)
    at com.yahoo.container.di.Container.waitForNextGraphGeneration(Container.java:75)
    at com.yahoo.container.core.config.HandlersConfigurerDi.waitForNextGraphGeneration(HandlersConfigurerDi.java:117)
    at com.yahoo.container.core.config.HandlersConfigurerDi.<init>(HandlersConfigurerDi.java:73)
    at com.yahoo.container.core.config.HandlersConfigurerDi.<init>(HandlersConfigurerDi.java:59)
    at com.yahoo.container.jdisc.ConfiguredApplication.createConfigurer(ConfiguredApplication.java:409)
    at com.yahoo.container.jdisc.ConfiguredApplication.start(ConfiguredApplication.java:168)
    at com.yahoo.jdisc.core.ApplicationLoader.start(ApplicationLoader.java:157)
    at com.yahoo.jdisc.core.StandaloneMain.run(StandaloneMain.java:41)
    at com.yahoo.jdisc.core.StandaloneMain.main(StandaloneMain.java:33)
Caused by: java.lang.RuntimeException: com.yahoo.jdisc.application.BundleInstallationException: Unable to cache bundle: file:/opt/vespa/var/db/vespa/filedistribution/5aaebad1c9543dcc/writing18378621176289283731
    at com.yahoo.osgi.OsgiImpl.install(OsgiImpl.java:156)
    at com.yahoo.container.core.config.FileAcquirerBundleInstaller.installBundles(FileAcquirerBundleInstaller.java:48)
    at com.yahoo.container.core.config.ApplicationBundleLoader.installWithFileDistribution(ApplicationBundleLoader.java:163)
    ... 14 more
Caused by: com.yahoo.jdisc.application.BundleInstallationException: Unable to cache bundle: file:/opt/vespa/var/db/vespa/filedistribution/5aaebad1c9543dcc/writing18378621176289283731
    at com.yahoo.jdisc.core.FelixFramework.installBundle(FelixFramework.java:87)
    at com.yahoo.osgi.OsgiImpl.install(OsgiImpl.java:154)
    ... 16 more
Caused by: org.osgi.framework.BundleException: Unable to cache bundle: file:/opt/vespa/var/db/vespa/filedistribution/5aaebad1c9543dcc/writing18378621176289283731
    at org.apache.felix.framework.Felix.installBundle(Felix.java:3258)
    at org.apache.felix.framework.BundleContextImpl.installBundle(BundleContextImpl.java:147)
    at org.apache.felix.framework.BundleContextImpl.installBundle(BundleContextImpl.java:120)
    at com.yahoo.jdisc.core.FelixFramework.installBundle(FelixFramework.java:183)
    at com.yahoo.jdisc.core.FelixFramework.installBundle(FelixFramework.java:85)
    ... 17 more
Caused by: java.util.zip.ZipException: zip END header not found
    at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1469)
    at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1477)
    at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1315)
    at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1277)
    at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:709)
    at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:243)
    at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:172)
    at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:186)
    at org.apache.felix.framework.util.SecureAction.openZipFile(SecureAction.java:802)
    at org.apache.felix.framework.util.WeakZipFileFactory$WeakZipFile.<init>(WeakZipFileFactory.java:169)
    at org.apache.felix.framework.util.WeakZipFileFactory$WeakZipFile.<init>(WeakZipFileFactory.java:151)
    at org.apache.felix.framework.util.WeakZipFileFactory.create(WeakZipFileFactory.java:78)
    at org.apache.felix.framework.cache.JarRevision.<init>(JarRevision.java:83)
    at org.apache.felix.framework.cache.BundleArchive.createRevisionFromLocation(BundleArchive.java:819)
    at org.apache.felix.framework.cache.BundleArchive.reviseInternal(BundleArchive.java:491)
    at org.apache.felix.framework.cache.BundleArchive.<init>(BundleArchive.java:155)
    at org.apache.felix.framework.cache.BundleCache.create(BundleCache.java:456)
    at org.apache.felix.framework.Felix.installBundle(Felix.java:3254)
    ... 21 more

1682102918.066649	564557cb9159	974/1	container	Container.com.yahoo.container.jdisc.ConfiguredApplication	info	Destroy: Shutting down container now
1682102918.073271	564557cb9159	974/1	container	Container.com.yahoo.container.jdisc.ConfiguredApplication	info	Destroy: Finished
1682102918.076220	564557cb9159	974/1	container	Container.com.yahoo.jdisc.core.StandaloneMain	error	JDisc exiting: Throwable caught:
exception=
java.lang.RuntimeException: Could not install bundle with reference 'file '5aaebad1c9543dcc''
    at com.yahoo.container.core.config.ApplicationBundleLoader.installWithFileDistribution(ApplicationBundleLoader.java:175)
    at com.yahoo.container.core.config.ApplicationBundleLoader.installBundles(ApplicationBundleLoader.java:149)
    at com.yahoo.container.core.config.ApplicationBundleLoader.useBundles(ApplicationBundleLoader.java:62)
    at com.yahoo.container.core.config.HandlersConfigurerDi$ContainerAndDiOsgi.useApplicationBundles(HandlersConfigurerDi.java:103)
    at com.yahoo.container.di.Container.installApplicationBundles(Container.java:205)
    at com.yahoo.container.di.Container.waitForNewConfigGenAndCreateGraph(Container.java:133)
    at com.yahoo.container.di.Container.waitForNextGraphGeneration(Container.java:75)
    at com.yahoo.container.core.config.HandlersConfigurerDi.waitForNextGraphGeneration(HandlersConfigurerDi.java:117)
    at com.yahoo.container.core.config.HandlersConfigurerDi.<init>(HandlersConfigurerDi.java:73)
    at com.yahoo.container.core.config.HandlersConfigurerDi.<init>(HandlersConfigurerDi.java:59)
    at com.yahoo.container.jdisc.ConfiguredApplication.createConfigurer(ConfiguredApplication.java:409)
    at com.yahoo.container.jdisc.ConfiguredApplication.start(ConfiguredApplication.java:168)
    at com.yahoo.jdisc.core.ApplicationLoader.start(ApplicationLoader.java:157)
    at com.yahoo.jdisc.core.StandaloneMain.run(StandaloneMain.java:41)
    at com.yahoo.jdisc.core.StandaloneMain.main(StandaloneMain.java:33)
Caused by: java.lang.RuntimeException: com.yahoo.jdisc.application.BundleInstallationException: Unable to cache bundle: file:/opt/vespa/var/db/vespa/filedistribution/5aaebad1c9543dcc/writing18378621176289283731
    at com.yahoo.osgi.OsgiImpl.install(OsgiImpl.java:156)
    at com.yahoo.container.core.config.FileAcquirerBundleInstaller.installBundles(FileAcquirerBundleInstaller.java:48)
    at com.yahoo.container.core.config.ApplicationBundleLoader.installWithFileDistribution(ApplicationBundleLoader.java:163)
    ... 14 more
Caused by: com.yahoo.jdisc.application.BundleInstallationException: Unable to cache bundle: file:/opt/vespa/var/db/vespa/filedistribution/5aaebad1c9543dcc/writing18378621176289283731
    at com.yahoo.jdisc.core.FelixFramework.installBundle(FelixFramework.java:87)
    at com.yahoo.osgi.OsgiImpl.install(OsgiImpl.java:154)
    ... 16 more
Caused by: org.osgi.framework.BundleException: Unable to cache bundle: file:/opt/vespa/var/db/vespa/filedistribution/5aaebad1c9543dcc/writing18378621176289283731
    at org.apache.felix.framework.Felix.installBundle(Felix.java:3258)
    at org.apache.felix.framework.BundleContextImpl.installBundle(BundleContextImpl.java:147)
    at org.apache.felix.framework.BundleContextImpl.installBundle(BundleContextImpl.java:120)
    at com.yahoo.jdisc.core.FelixFramework.installBundle(FelixFramework.java:183)
    at com.yahoo.jdisc.core.FelixFramework.installBundle(FelixFramework.java:85)
    ... 17 more
Caused by: java.util.zip.ZipException: zip END header not found
    at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1469)
    at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1477)
    at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1315)
    at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1277)
    at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:709)
    at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:243)
    at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:172)
    at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:186)
    at org.apache.felix.framework.util.SecureAction.openZipFile(SecureAction.java:802)
    at org.apache.felix.framework.util.WeakZipFileFactory$WeakZipFile.<init>(WeakZipFileFactory.java:169)
    at org.apache.felix.framework.util.WeakZipFileFactory$WeakZipFile.<init>(WeakZipFileFactory.java:151)
    at org.apache.felix.framework.util.WeakZipFileFactory.create(WeakZipFileFactory.java:78)
    at org.apache.felix.framework.cache.JarRevision.<init>(JarRevision.java:83)
    at org.apache.felix.framework.cache.BundleArchive.createRevisionFromLocation(BundleArchive.java:819)
    at org.apache.felix.framework.cache.BundleArchive.reviseInternal(BundleArchive.java:491)
    at org.apache.felix.framework.cache.BundleArchive.<init>(BundleArchive.java:155)
    at org.apache.felix.framework.cache.BundleCache.create(BundleCache.java:456)
    at org.apache.felix.framework.Felix.installBundle(Felix.java:3254)
    ... 21 more

1682102918.072747	564557cb9159	1005/1	metricsproxy-container	Container.com.yahoo.container.handler.threadpool.ContainerThreadpoolImpl	info	Threadpool 'default-pool': min=1, max=1, queue=50
1682102918.159864	564557cb9159	938/49650	config-sentinel	sentinel.sentinel.service	event	stopped/1 name="container" pid=974 exitcode=6
1682102918.163494	564557cb9159	938/49650	config-sentinel	sentinel.sentinel.service	info	container: incremented restart penalty to 2.000 seconds
```

```
[eco ~]$tree /opt/baz/vespa/var/db/vespa/filedistribution/
/opt/baz/vespa/var/db/vespa/filedistribution/
├── 5aaebad1c9543dcc
│   └── writing18378621176289283731
│       └── basic-application-1.0.1-deploy.jar
└── e385674f5aa53029
    └── writing13040323703060982703
        └── 2
            ├── build-meta.json
            ├── components
            │   └── basic-application-1.0.1-deploy.jar
            ├── hosts.xml
            ├── schemas
            │   └── bazdocs.sd
            └── services.xml

8 directories, 6 files
```

[vespa-simple-with-bundle.zip](https://github.com/vespa-engine/vespa/files/11298708/vespa-simple-with-bundle.zip)

**Comment by hmusum** [comment] 2023-04-23 18:00
I am unable to reproduce this with version 8.86.28 following the quick start guide (https://docs.vespa.ai/en/vespa-quick-start.html). The file tree looks like expected when doing this:

` tree /opt/vespa/var/db/vespa/filedistribution/
/opt/vespa/var/db/vespa/filedistribution/
└── 29935d50dc2455db
    └── 2
        ├── README.md
        ├── ext
        │   ├── A-Head-Full-of-Dreams.json
        │   ├── Hardwired...To-Self-Destruct.json
        │   ├── Liebe-ist-fur-alle-da.json
        │   ├── Love-Is-Here-To-Stay.json
        │   └── When-We-All-Fall-Asleep-Where-Do-We-Go.json
        ├── schemas
        │   └── music.sd
        └── services.xml

4 directories, 8 files`

The directory `writing18378621176289283731` you are seeing is a temporary directory that should be removed when deploy has finished successfully. Are you sure it did? I would guess there are warnings or errors in the vespa log for component configserver (use `vespa-logfmt -S configserver` to show only those) if this fails, can you see if you find any?

**Comment by codycollier** [comment] 2023-04-23 19:20
Thank you for the followup Harald.  The error only occurs if there's a java component/bundle included.

I was just able to re-create it with the `album-recommendation-java` sample application (same errors as my test app).  This time it was on `8.155.19`, and a completely fresh start with empty underlying directories etc.

```
> cd ./album-recommendation-java/
> mvn package
> cd target/application/
> vespa deploy
# deploy succeeds
# then same errors as above in vespa log (container server fails to start)
```

There are no other errors in the log (for configserver or any other service).

**Comment by codycollier** [comment] 2023-04-23 19:22
```
[eco ~]$tree /opt/baz/vespa/var/db/vespa/filedistribution/
/opt/baz/vespa/var/db/vespa/filedistribution/
├── 6edf3773c50968d5
│   └── writing15246786986170763366
│       └── album-recommendation-java-deploy.jar
└── baf2e2772b0494f1
    └── writing4560160161425432542
        └── 2
            ├── build-meta.json
            ├── components
            │   └── album-recommendation-java-deploy.jar
            ├── schemas
            │   └── music.sd
            └── services.xml

8 directories, 5 files
```

**Comment by hmusum** [comment] 2023-04-23 22:17
I have just tried running the [Quick start Java guide](https://docs.vespa.ai/en/vespa-quick-start-java.html) with 8.155.19 and it works fine for me. I wonder why you `tree` command is using `/opt/baz/vespa/var/db/vespa/filedistribution/` and not `/opt/vespa/var/db/vespa/filedistribution/`? Does the error messages in vespa log also refer to `/opt/baz/vespa/var/db/vespa/filedistribution/`? (they didn't in you original description)

**Comment by codycollier** [comment] 2023-04-23 23:28
That's interesting.  I see two differences from the quick start guide, in my local recreation.  One is that I'm using a docker bind mount to mount the logs and var directories from the host into the container.  The second is that I was using mvn package instead of mvn install.

(The path difference for tree can be ignored for now.  That's just because I ran tree from the host instead of inside the container, so the path is slightly different.)

Let me go test without a bind mount etc and see if that makes a difference.  

Is it possible something changed in 8.86.28 (and after) which prevents this from working with a docker bind mount?  Could it be related to this: [Add flag for using locks in file distribution
](https://github.com/vespa-engine/vespa/commit/769cef542e57fd8538ae184c8c17701443807616)

**Comment by codycollier** [comment] 2023-04-24 00:05
I confirmed in local testing, that using bind mount volumes leads to the error. The related documentation for starting vespa is here:

* https://docs.vespa.ai/en/operations/docker-containers.html#mounting-persistent-volumes

Here's my history showing how I started the container:
```
> mkdir -p /tmp/vespa/var;  export VESPA_VAR_STORAGE=/tmp/vespa/var
> mkdir -p /tmp/vespa/logs; export VESPA_LOG_STORAGE=/tmp/vespa/logs
> docker run --detach --name vespa --hostname vespa-container   --volume $VESPA_VAR_STORAGE:/opt/vespa/var   --volume $VESPA_LOG_STORAGE:/opt/vespa/logs   --publish 8080:8080 --publish 19071:19071 vespaengine/vespa
```

Starting vespa like this, with bind mount volumes, and then deploying the album-recommendation-java app, results in the same internal java exception and container error about file distribution etc.  Conversely, starting the docker container without mounted dirs (like in the quickstart guide), and there's no error.

**Comment by codycollier** [comment] 2023-04-24 04:04
I got a little engrossed, and started doing some debug logging for the config server, both with and without using a docker bind mount style volume.  As you previously noted, one would expect an error from the config server if the tmp directories were still in place after the filedistribution work.

The following is a bit speculative, but only a small number of filedistribution things changed in 8.86.28.  It looks like there might be a subtle portability bug in this diff:
* https://github.com/vespa-engine/vespa/commit/d84d60c3a1f9fd4347365ddb935bb215233681d5

The use of `renameTo()` was carried over from red line 148 to green line 151.  However, red line 148 was never run. Note how a directory was created in red line 138 and then existence was tested in red line 146.  Essentially, the `renameTo()` was never run in the old version and this section of code always fell back to `IOUtils.copyDirectory()`.  

The java docs indicate renameTo behavior is platform dependent, and might not even be atomic. This also happens to be the only place it's used in the code base (except a test). Maybe it behaves unexpectedly when used to move files on a mounted volume inside a container?

**Comment by hmusum** [comment] 2023-04-24 12:17
@codycollier thanks very much for debugging and suggesting what might be the issue! I think you found exactly where the problem lies. A fix has gone into 8.157, which should hopefully be out tomorrow.

**Comment by codycollier** [comment] 2023-04-24 14:53
Thanks @hmusum! I really appreciate the interactions and such a quick turnaround. I'll keep an eye out for the release.

**Comment by hmusum** [comment] 2023-04-26 10:24
8.157.14 has been released with the fix, please reopen if this is still an issue

**Closed by hmusum** 2023-04-26 10:24 UTC

**Comment by codycollier** [comment] 2023-04-26 15:43
Everything looks like it's back to normal now with 8.157.14.  Thanks!
