### ISSUE TITLE
cluster down while feeding large number of documents

### ISSUE THREAD

**Issue by shubh9194** [vespa-engine/vespa#25810] opened 2023-01-31 06:55 UTC
**Describe the bug**
Hi, I faced an issue while trying to large number of documents in vespa cluster having 12 content nodes.
cluster has 2 groups. each group having 6 content nodes.
i am using an implementation similar to jsonFileFeeder to feed the docs.
cluster went down after feeding few million docs. I checked the logs and found the following error.

1675145234.326723       qa-content-0.qa-internal.d19.svc.cluster.local     25871    searchnode      stderr  warning vespa-proton-bin: /builddir/build/BUILD/vespa-8.82.24/vespalib/src/vespa/vespalib/datastore/buffer_type.cpp:153: virtual size_t vespalib::datastore::BufferTypeBase::calcArraysToAlloc(uint32_t, vespalib::datastore::BufferTypeBase::ElemCount, bool) const: Assertion `result >= neededArrays' failed.
1675145238.423702       qa-content-0.qa-internal.d19.svc.cluster.local     491/41265        config-sentinel sentinel.sentinel.service       event   crash/1 name="searchnode" pid=25871 signal="Aborted"
1675145238.426273       qa-content-0.qa-internal.d19.svc.cluster.local     491/41265        config-sentinel sentinel.sentinel.service       info    searchnode: incremented restart penalty to 1800.000 seconds

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - Infrastructure: Kubernetes

**Vespa version**
8.82.24

Let me know if you need more info.
unable to bring the cluster up. Tried restarting the nodes but seeing the above error msg in logs

**Comment by baldersheim** [comment] 2023-02-01 14:53
We have had a look at this issue today. As this is an explicit assert it means that it is a condition that should not be possible.
After we have investigated the code we have found 2 situations what can trigger this.
1 - A single word that is longer than 16MB in a field with indexing:index.
2 - A single document with a very large field with more than 4MB occurrences of a single word, also with indexing:index.
3 - A logic flaw that we were not able to find by code inspection.

We have made a PR that will shed some more light on what it causing this in #25838. When that is merged you will get more information in the log enabling us to pinpoint the issue better.

An alternative is to inspect the issue with a debugger (gdb) and the a coredump if it is/can be enabled. Then it is possible extract the information now. But that requires some knowledge of debugging. If you want to go this way we can assist.
But then we probably need to use slack or similar. What is your timezone ?

**Comment by shubh9194** [comment] 2023-02-02 13:34
thanks @baldersheim 
I have found the document that caused this issue. for now, We are trying to find a way to figure out whether we have more similar documents that can cause this issue.

whenever this document is ingested, whole cluster went down and we are unable to bring the cluster up.
I was able to bring the cluster up only after removing the data by running following cmd in content nodes
/opt/vespa/bin/vespa-stop-services && /opt/vespa/bin/vespa-remove-index -force && /opt/vespa/bin/vespa-start-services

But right now, even after running the above cmd, my cluster is still down. 
Is there any other way to check whether the whole data is removed when cluster is down.

**Comment by jobergum** [comment] 2023-02-06 13:48
>I don't understand what you mean by 4mb occurrences of a single word in 2nd situation.

That a single word repeats 4MB times in the same document. 

>I was able to bring the cluster up only after removing the data by running following cmd in content nodes
>/opt/vespa/bin/vespa-stop-services && /opt/vespa/bin/vespa-remove-index -force && /opt/vespa/bin/vespa-start-services

That wipes all data, and after starting the cluster (and waiting for all services) the cluster should be good to go.

**Comment by bratseth** [comment] 2023-02-06 20:57
4**M** occurrences, I think.

**Comment by baldersheim** [comment] 2023-03-30 12:27
No, you need to upgrade to a recent version and see if the issue still persist.
We have added logging that will pinpoint more that root cause is.
If you have a document that will reproduce the issue, you can provide that a the searchdefinition and we can pinpoint it ourselves.
So far no more action planned from our side until further information is available.

**Comment by baldersheim** [comment] 2023-05-02 18:58
No more information available. Assuming fixed. reopen with addition information if problem still persist.

**Closed by baldersheim** 2023-05-02 18:58 UTC
