### ISSUE TITLE
https://vespa.ai has a self signed or invalid cert

### ISSUE THREAD

**Issue by harryjackson** [vespa-engine/vespa#3545] opened 2017-09-27 04:21 UTC
I would add this to the front_page repo but I didn't see how to add an issue. You can get a free certificate via: https://letsencrypt.org/ if time is an issue.

**Comment by frodelu** [comment] 2017-09-27 06:22
Thank you for your input @harryjackson.

We are currently serving vespa.ai out of GitHub Pages and they, unfortunately, do not (properly) support HTTPS for custom domains as we cannot add our own certificate.

We may look at a different serving option in the future or can hope GitHub will add support for this. For now, I am afraid we will have to do with plain, insecure HTTP.

Best regards,
Frode Lundgren
Director of Engineering, Vespa Services

**Comment by frodelu** [comment] 2018-06-05 19:00
Since closing this issue, GitHub has started issuing Let's Encrypt certificates for all GitHub Pages custom domains. https://docs.vespa.ai now has a valid certificate, but https://vespa.ai still use the generic GitHub certificate. Will continue to keep an eye on this.

**Comment by frodelu** [comment] 2018-06-05 19:21
Just found that the reason we don't have valid certificate for apex domain (vespa.ai) is that GitHub have changed what A records to use to get Let's Encrypt certificate.

From https://help.github.com/articles/troubleshooting-custom-domains/#custom-domains-configured-with-a-records:
> If you configured your custom domain using an A record, your A record must point to one of the following IP addresses for HTTPS to work:
> 
> * 185.199.108.153
> * 185.199.109.153
> * 185.199.110.153
> * 185.199.111.153

I have updated the A records for vespa.ai:
```
$ dig +noall +answer vespa.ai
vespa.ai.		583	IN	A	185.199.111.153
vespa.ai.		583	IN	A	185.199.108.153
vespa.ai.		583	IN	A	185.199.109.153
vespa.ai.		583	IN	A	185.199.110.153
```

I have removed and re-added custom domain (vespa.ai) to GitHub pages hoping this would trigger certificate generation.

**Comment by frodelu** [comment] 2018-06-05 19:33
Confirmed that SSL certificate for https://vespa.ai is now valid:
https://www.digicert.com/help/?host=vespa.ai

**Closed by frodelu** 2018-06-05 19:33 UTC
