### ISSUE TITLE
Getting same record on multiple pages, when implemented pagination in vespa

### ISSUE THREAD

**Issue by yashkasat** [vespa-engine/vespa#12497] opened 2020-03-07 14:10 UTC
I am getting same record on different pages when implementing pagination using group by.

I am using the query mentioned below:

`http://<hostname>:<port>/search/?yql=select * from sources document_name where sddocname contains 'document_name' limit 0 | [{ 'continuations':['this_value','next_value'] }] all(group(key) max(2) each(each(output(summary()))));`

**Comment by andreer** [comment] 2020-03-09 12:34
Search definition for field is "field key type string { indexing: summary | attribute }"

**Comment by andreer** [comment] 2020-03-09 15:13
Attempted to reproduce this today and I did get some surprising behavior. Will verify tomorrow whether this is a bug or just a non-intuitive result.

**Comment by griseau** [comment] 2020-03-10 09:02
Hi @yashkasat, I already faced this issue and solution I found was to add an order clause after the max clause. In my case it was something like : `| all(group(foo) max(2) order(-count()) each(output(count())))`

**Comment by andreer** [comment] 2020-03-10 12:29
Thank you @griseau - Yes, this will help, but ordering the groups descending by count will not be desirable in all use cases, so I'll expand a bit.

You need a (stable) ordering of the hits for pagination by continuations to work well. This is usually the case as in most use cases there will be a ranking expression in place.

The default ordering in grouping expressions is by rank - in grouping expression syntax this would be order(max(relevance())).

The query above only limits on document type. All documents of that document type will match this query equally well. I tested this using the "album-recommendation-selfhosted" sample app, and relevance was 0 for all documents. When the relevance is the same for all documents, the order will essentially be random. The same thing may occur when doing order(-count()) if count() is the same for several groups.

I was able to achieve the expected results by adding and using a ranking profile using the random.match rank feature: https://docs.vespa.ai/documentation/reference/rank-features.html#random 
I believe this should ensure a stable ordering of hits, although this may still produce different results if the query is dispatched to different content hosts. If you need a stable global ordering, consider storing a random float/double to each document to rank/order by - this can also be used as a "tie breaker" to help ensure a stable order from ranking expressions.

I will add a paragraph to our documentation about this, and we will consider whether we should make some other change here.

**Comment by griseau** [comment] 2020-03-11 09:51
Hi @andreer , thanks for your answer ! 

I actually faced this issue yesterday when having same number of count over different groups. 
I have a field 
```
set_of_words type array<string> {
            indexing: summary | attribute
        }
```

When I try to run this query `all(group(set_of_words) max(100) order(-count()) each(output(count())))` I have some results multiple times. 
Adding a random float or double to my documents won't fix this case. Do you have any suggestion, or should I open a new issue for it ? 

Thanks !

**Comment by jobergum** [comment] 2020-03-11 10:28
@griseau is your question in the context of pagination?

**Comment by griseau** [comment] 2020-03-11 10:33
@jobergum Yes

**Comment by jobergum** [comment] 2020-03-11 10:54
Please open a separate issue on this @griseau, and include as much details as you can. Number of nodes in your content cluster and so on.

**Comment by andreer** [comment] 2020-03-11 10:55
I think adding a ranking expression using random.match might still help - or if your documents have a field "tiebreaker" with a value from 0.0-1.0 then you could change your order clause to include this, like order(10*count() + max(tiebreaker)). Unfortunately I don't have time to positively verify this today.

**Comment by jobergum** [comment] 2020-03-11 13:20
I'm resolving this, @griseau: appreciate a new issue on your problem, since it's not top N grouping I don't see how document ordering impacts this, but suspecting that your problem is related to grouping on multi-valued fields.

**Closed by jobergum** 2020-03-11 13:20 UTC
Labels: question
