### ISSUE TITLE
Exceptions while performing Vespa Visit operation

### ISSUE THREAD

**Issue by 107dipan** [vespa-engine/vespa#30709] opened 2024-03-21 15:06 UTC
**Describe the bug**
WE have an application which is using vespa visit operation to fetch documents from vespa cluster. The cluster we are testing on has node acting as config/container node and another node which is acting as a content nodes. 

I am making multiple parallel visit calls on different schemas. Most of the visit calls are fetching very few documents. 

> [2024-03-20 20:34:31.528] WARNING container        Container.com.yahoo.document.restapi.resource.DocumentV1ApiHandler   Error writing documents\nexception=\njava.lang.RuntimeException: Failing due to earlier ServletOutputStream write failure\n\tat com.yahoo.jdisc.http.server.jetty.ServletOutputStreamWriter.failAllParts_holdingLock(ServletOutputStreamWriter.java:205)\n\tat com.yahoo.jdisc.http.server.jetty.ServletOutputStreamWriter.setFinished(ServletOutputStreamWriter.java:187)\n\tat com.yahoo.jdisc.http.server.jetty.ServletOutputStreamWriter.writeBuffersInQueueToOutputStream(ServletOutputStreamWriter.java:177)\n\tat com.yahoo.jdisc.http.server.jetty.ServletOutputStreamWriter$1.onWritePossible(ServletOutputStreamWriter.java:272)\n\tat org.eclipse.jetty.server.HttpOutput.run(HttpOutput.java:1494)\n\tat org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1466)\n\tat org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:597)\n\tat org.eclipse.jetty.server.HttpChannel.run(HttpChannel.java:461)\n\tat org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969)\n\tat org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194)\n\tat org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149)\n\tat java.base/java.lang.Thread.run(Thread.java:840)\nCaused by: org.eclipse.jetty.io.EofException: Closed\n\tat org.eclipse.jetty.server.HttpOutput.checkWritable(HttpOutput.java:756)\n\tat org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:780)\n\tat com.yahoo.jdisc.http.server.jetty.ServletOutputStreamWriter.lambda$writeBufferToOutputStream$4(ServletOutputStreamWriter.java:220)\n\tat com.yahoo.jdisc.http.server.jetty.ServletOutputStreamWriter.callCompletionHandlerWhenDone(ServletOutputStreamWriter.java:236)\n\tat com.yahoo.jdisc.http.server.jetty.ServletOutputStreamWriter.writeBufferToOutputStream(ServletOutputStreamWriter.java:215)\n\tat com.yahoo.jdisc.http.server.jetty.ServletOutputStreamWriter.writeBuffersInQueueToOutputStream(ServletOutputStreamWriter.java:174)\n\t... 9 more\n
[2024-03-20 20:34:45.139] WARNING container        Container.com.yahoo.jdisc.http.server.jetty.ReferenceCountingRequestHandler  Uncaught completion failure.\nexception=\njava.lang.IllegalStateException: ContentChannel already closed.\n\tat com.yahoo.jdisc.http.server.jetty.ServletOutputStreamWriter.lambda$writeBuffer$0(ServletOutputStreamWriter.java:86)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)\n\tat java.base/java.lang.Thread.run(Thread.java:840)\n
[2024-03-20 20:34:45.141] WARNING container        Container.com.yahoo.jdisc.http.server.jetty.ReferenceCountingRequestHandler  Uncaught completion failure.\nexception=\njava.lang.IllegalStateException: ContentChannel already closed.\n\tat com.yahoo.jdisc.http.server.jetty.ServletOutputStreamWriter.lambda$writeBuffer$0(ServletOutputStreamWriter.java:86)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)\n\tat java.base/java.lang.Thread.run(Thread.java:840)\n

Could you help us understand what the issue might be

**Vespa version**
8.294.50

**Comment by bjorncs** [comment] 2024-03-26 08:23
Hi @107dipan.

It's caused by the client abruptly closing the connection before the response is fully written. Typically it's a result of the client having a stricter timeout than the server. You will observe this as an I/O or timeout failure client side. The access log for jdisc should give you a hint what the client timeout is configured to.

Logging was warning with a stack trace gives the impression that it's a critical failure. We're reducing the log level in the upcoming release to something more fitting (https://github.com/vespa-engine/vespa/pull/30734).

**Closed** 2024-04-03 11:14 UTC
