### ISSUE TITLE
VESPA_UNPRIVILEGED is not working as intended

### ISSUE THREAD

**Issue by vfil** [vespa-engine/vespa#12524] opened 2020-03-10 10:30 UTC
Sometimes we don't have a privileged user to run vespa or there are some constraints on setting the upper limit on opened files on the OS. An example would be Continous Integration platforms like circleci.
I find this kind of setup would be useful for integration tests as a part of the CI pipeline. 
After a quick investigation, I found VESPA_UNPRIVILEGED flag which can be used to skip the `ulimit -n` step on Vespa startup. Unfortunately, this didn't work.
Here are quick steps to reproduce:
```
~:10:36:50> docker run -it --entrypoint="" vespaengine/vespa:7.187.1 bash
Unable to find image 'vespaengine/vespa:7.187.1' locally
7.187.1: Pulling from vespaengine/vespa
ab5ef0e58194: Already exists
08675e7c50bb: Pull complete
dca856248da6: Pull complete
d9b2e4ffcc68: Pull complete
Digest: sha256:51be5b16ef27b8ca23e177ab45a856196110870db9aaf919933c184c95ebe26b
Status: Downloaded newer image for vespaengine/vespa:7.187.1
[root@94b19cd1237a /]# ulimit -n 65000
[root@94b19cd1237a /]# export VESPA_UNPRIVILEGED=yes
[root@94b19cd1237a /]# /usr/local/bin/start-container.sh &
[1] 19
[root@94b19cd1237a /]# hostname: you must be root to change the host name
Running /opt/vespa/libexec/vespa/start-configserver
Creating data directory /opt/vespa/var/zookeeper/version-2
/opt/vespa/libexec/vespa/common-env.sh: line 178: ulimit: open files: cannot modify limit: Operation not permitted

[1]+  Exit 1                  /usr/local/bin/start-container.sh
[root@94b19cd1237a /]# echo $VESPA_UNPRIVILEGED
yes
```
I suppose vespa startup script is calling `ulimit -n` here https://github.com/vespa-engine/vespa/blob/5d657d4537d753b09f9cedce19f785c35eba2d80/vespabase/src/common-env.sh#L178 hence the error:
`/opt/vespa/libexec/vespa/common-env.sh: line 178: ulimit: open files: cannot modify limit: Operation not permitted` and vespa doesn't start.

**Comment by aressem** [comment] 2020-03-10 13:05
I have looked into this and in `/opt/vespa/conf/vespa/default-env.txt` there is an override for the VESPA_UNPRIVILEGED to `no`. This means that it will be overridden regardless of the environment you set. If you change the VESPA_USER and VESPA_UNPRIVILEGED to these values:
```
override VESPA_USER root
override VESPA_UNPRIVILEGED yes
```
you should get the expected behaviour.

**Comment by vfil** [comment] 2020-03-10 13:32
very helpful info, editing the file and setting `override VESPA_UNPRIVILEGED yes` works. Would be nice if env var would take the precedence, but I guess can make use of sed editor.

**Comment by aressem** [comment] 2020-03-10 13:34
You should also be able to remove those overrides to use the env variable instead. And you could bind mount that default-env.txt from your host environment.

**Comment by vfil** [comment] 2020-03-10 13:50
That makes sense, useful to include this in the docs. Can put a PR for documenting this configuration.

**Comment by aressem** [comment] 2020-03-11 06:45
That would be helpful and welcome. I'm closing this issue now that a solution has been found.

**Closed by aressem** 2020-03-11 06:45 UTC

**Comment by tkaessmann** [comment] 2022-09-02 13:11
We also had that issue in our docker environment on ec2 and the following mount helped us a lot (**because you're not able to set this via an `env` variable in the docker run**):
```
docker run -d \
   ...
   --volume "/app/default-env.txt:/opt/vespa/conf/vespa/default-env.txt" \
   ...
   vespaengine/vespa
```
The content of `/app/default-env.txt` is:
```
override VESPA_UNPRIVILEGED yes
```

**Comment by aressem** [comment] 2022-11-01 09:28
This workaround has stopped working with Vespa `8.75.16` due the VESPA_UNPRIVILEGED flag being removed. We are currently working on supporting this properly and the new workaround for now is to run as the vespa user by supplying the argument `--user vespa` to the commandline.

**Comment by tomglk** [comment] 2022-11-01 11:15
Thanks for your suggestion to fix this @aressem .

The docker run from @tkaessmann does not work anymore. This works:

```bash
docker run -d \
    --name vespa \
    --user vespa \
    --hostname vespa-container \
    --publish 8080:8080 \
    --publish 19071:19071 \
    vespaengine/vespa
```
