### ISSUE TITLE
Error with docker image version 8.184.20

### ISSUE THREAD

**Issue by danitico** [vespa-engine/vespa#27565] opened 2023-06-28 07:55 UTC
**Describe the bug**
When I deploy a vespa package using the version 8.184.20 I encounter the following error and then, an incremented restart penalty is applied to the searchnode:

```
WARNING searchnode       stderr   Not able to unmap (nil) as it is not registered: _ZN4llvm14verifyFunctionERKNS_8FunctionEPNS_11raw_ostreamE(0xffff752c48b4)
```

```
WARNING searchnode       stderr   (0xffff7ea6bdcc) from _ZdlPvmSt11align_val_t(0xffff7ea682e8) from (0xffff752c4520) from _ZN4llvm14verifyFunctionERKNS_8FunctionEPNS_11raw_ostreamE(0xffff752c48b4) from _ZN8vespalib4eval11LLVMWrapper13make_functionEmNS0_10PassParamsERKNS0_5nodes4NodeERKSt6vectorIPFNS0_4gbdt8Optimize6ResultERKNS8_11ForestStatsERKS7_IPS5_SaISE_EEESaISK_EE(0xffff7bee1864) from _ZN8vespalib4eval16CompiledFunctionC1ERKNS0_5nodes4NodeEmNS0_10PassParamsERKSt6vectorIPFNS0_4gbdt8Optimize6ResultERKNS8_11ForestStatsERKS7_IPS4_SaISE_EEESaISK_EE(0xffff7bedaccc) from _ZN8vespalib4eval12CompileCache11CompileTask3runEv(0xffff7bed79a8) from (0xffff7bc3e874) from _ZN8vespalib23ThreadStackExecutorBase3runEv(0xffff7bc872a0) from _Z22proton_shared_executorRN8vespalib8RunnableE(0x5384dc) from (0xffff72b82d2c) from (0xffff7ea6c5e4) from
```

However, when I am using v8.181.15 this error does not happen.

**To Reproduce**
1. Deploy an application
2. Wait for error

**Expected behavior**
It should deploy correctly

**Screenshots**
No applicable

**Environment (please complete the following information):**
 - OS: macOS
 - Infrastructure: self-hosted
 - Versions: 8.184.20

**Vespa version**
8.184.20

**Additional context**
No

**Comment by kkraune** [comment] 2023-06-28 08:21
Thanks for reporting! We have confirmed the problem and working on a fix - please versions prior to 8.184.20

**Comment by aressem** [comment] 2023-06-28 09:14
I have moved the tags `8` and `latest` to point to the previous `8.181.15` release now until we figure out what the problem is.

**Comment by baldersheim** [comment] 2023-06-28 11:39
Fixed by #27566 in 7.186.8

**Comment by bratseth** [comment] 2023-06-28 12:17
**8**.186.8

**Comment by baldersheim** [comment] 2023-06-29 20:14
8.186.15 with the fix has been released and all should be good and back to normal.
This revealed an issue with our release pipeline. The docker image used for testing is built early, and once all tests have passed the release is rebuilt by copr. Then a smaller subset of the tests are rerun.  It turns out that uses the latest centos-stream package set. So if there are released updated packages to the centos-stream repo there will be a difference in set of packages used during the full test cycle, and the final build on copr with reduced test run.
This flaw will be addressed to avoid this dual staged build cycle.

**Closed by baldersheim** 2023-06-29 20:14 UTC
Labels: bug
