### ISSUE TITLE
weightedset create-if-nonexistent/remove-if-zero triggers "Got datatype tag"

### ISSUE THREAD

**Issue by jobergum** [vespa-engine/vespa#23334] opened 2022-07-04 07:15 UTC
Copied from https://gitter.im/vespa-engine/Lobby#

Given the field is declared as :

``` field searchKeywords type weightedset<string> {
            indexing: summary | index
            weightedset {
                create-if-nonexistent
                remove-if-zero
            }
            stemming: multiple
            match: text
        }
```
And the document is put as:

```
{
    "fields": {
          ...
          "searchKeywords": {
              "key_1": 1,
              "key_2": 1
           }
           ....
    }
}
```
Then Http 502 is returned:

```
{
    "pathId": "<xxx>",
    "id": "<xxx>",
    "message": "[UNKNOWN(252001) @ tcp/vespa:19101/chain.indexing]: Processing failed. Error message: java.lang.IllegalArgumentException: Incompatible data types. Got datatype tag (code: 18), expected datatype WeightedSet<string> (code: 1328286588) -- See Vespa log for details. "
}
```

If the weightedset block is removed - all works as expected:
```
field searchKeywords type weightedset<string> {
            indexing: summary | index
            stemming: multiple
            match: text
        }
```

**Comment by jobergum** [comment] 2022-07-04 07:17
I think this could be related to the that these settings imply attribute matching (word). I don't see how these settings can work with `index` unless one does an expensive lookup in the summary store.

**Comment by arnej27959** [comment] 2022-07-06 13:52
this should "just work", and when I try to reproduce there is no problem.
note that the reported Vespa version (7.488.67) is from October 2021; the issue is probably fixed in the meantime.
User should upgrade to Vespa 8.

**Closed by arnej27959** 2022-07-06 13:52 UTC
